# Generated by Django 4.1.1 on 2022-10-26 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('descr', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=30)),
                ('price', models.IntegerField(max_length=4)),
                ('picture', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'books',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=30)),
                ('login', models.CharField(max_length=20)),
                ('passwd', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(max_length=4)),
                ('order_date', models.DateField()),
                ('pay_date', models.DateField()),
                ('deliv_date', models.DateField()),
                ('status', models.CharField(max_length=1)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab1.books')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab1.users')),
            ],
            options={
                'db_table': 'orders',
                'managed': True,
            },
        ),
    ]
